services:
  xss-app:
    build:
      context: .
      dockerfile: dockerfile-victim
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/code/logs
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Bangkok
    networks:
      my-network:
        ipv4_address: 172.20.0.3

  waf:
    build:
      context: .
      dockerfile: dockerfile-waf
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/code/logs
    environment:
      - FLASK_ENV=development
      - TZ=Asia/Bangkok
    networks:
      my-network:
        ipv4_address: 172.20.0.2

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
